### ISSUE TITLE
BUG - Unit tests fail on new repo

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/DEMO-BITS#9]
**Describe the bug**

![Image](https://github.com/user-attachments/assets/5056d75b-a825-4c79-9537-92332a8b959c)

**To Reproduce**
 Followed the `README` instructions assiduously.

**Expected behavior**

No problems.

**Environment (please complete the following information):**

GitHub web interface

**Comment by prjemian** [comment]
```text
              ********************************************************************************
              Please use a simple string containing a SPDX expression for `project.license`. You can also use `project.license-files`. (Both options available on setuptools>=77.0.0).
      
              By 2026-Feb-18, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
      
              See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
              ********************************************************************************
```

Done that in a couple other repos recently.  Will do here as well.

**Comment by prjemian** [comment]
This [commit ](https://github.com/BCDA-APS/16bm-bits/commit/a4a605e147223a6650c2e2590e8fb081631bdc60)has the correct licensing keys (under the `[project]` group).

**Comment by prjemian** [comment]
Then, another problem:

```
  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [2 lines of output]
      running egg_info
      error: error in 'egg_base' option: 'src' does not exist or is not a directory
      [end of output]
```

**Comment by prjemian** [comment]
@ravescovi I believe [this](https://github.com/BCDA-APS/16bm-bits/blob/a4a605e147223a6650c2e2590e8fb081631bdc60/pyproject.toml#L79-L80) is the offender:

![Image](https://github.com/user-attachments/assets/6de6ef83-eb23-44c6-a4a9-82b352c92caf)

Can you advise?

**Comment by prjemian** [comment]
Practicing the changes needed in the the new 16bm-bits repo.  Once the config is correct and the workflow runs, I'll apply the same changes in the `BITS-Starter` repo, then rebuild the `16bm-bits` repo per instructions.

**Comment by ravescovi** [comment]
Can bring back the `src` folder into main (even if it is empty). I checked and it should pass the error. What you think?

**Comment by ravescovi** [comment]
I don't see how to reproduce it. The first thing is to install `pure` apsbits then create an instrument. Which will create the src folder. It seems the error happens even before that, when github clones the repo and runs the "first" gha.

**Comment by prjemian** [comment]
Looking at https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html, this structure might be used.  What do you think?

```toml
[tool.setuptools.packages.find]
where = ["src"]  # list of folders that contain the packages (["."] by default)
# include = ["my_package*"]  # package names should match these glob patterns (["*"] by default)
exclude = ["*_qserver*"]  # exclude packages matching these glob patterns (empty by default)
namespaces = false  # to disable scanning PEP 420 namespaces (true by default)
```

But the real problem here is that there is no `src/` directory when the project is first created.  Do we just tolerate workflow failure in this case?
